markdown: kramdown
baseurl: /jekyll-onna
website-title: Website title
exclude: ['README.md', '.gitignore']
permalink: pretty
email: contact@your.email.address
social:
  - provider: facebook
    account-id:
  - provider: instagram
    account-id:
  - provider: twitter
    account-id:
include-analytics-tracking: false
google-api-key:
analytics :
  provider : google
  google :
    tracking_id :
disqus:
  comments: true
  url: demodchantzis.disqus.com
collections:
  albums:
    output: true
    permalink: /albums/:path/
  videos:
    output: true
    permalink: /videos/:path/
display-social-media-share-buttons: true
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
paginate: 5
paginate_path: "/news/page:num/"
